name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.302'

      - name: Restore dependencies
        run: dotnet restore 
        working-directory: backend/GameBackend/API

      - name: Build project
        run: dotnet build --configuration Release 

      - name: Run tests
        run: dotnet test --configuration Release 
